FROM poldracklab/fmriprep:20.2.0

# Verificarlo
RUN apt-get -y update && apt install -y llvm-8 llvm-8-dev clang-8 libmpfr-dev autotools-dev automake

RUN git clone https://github.com/verificarlo/verificarlo.git && \
    (cd verificarlo && git checkout v0.4.2 && ./autogen.sh && \
    ./configure --without-flang --with-llvm=$(llvm-config-8 --prefix))

RUN (cd verificarlo && make && make install)

ENV VFC_BACKENDS "libinterflop_mca.so --precision-binary32 25 --precision-binary64 25 --mode rr"

# libmathwrapper
RUN git clone https://github.com/big-data-lab-team/MCA-libmath.git /lib/MCA-libmath && \
    (cd /lib/MCA-libmath/src && make)

ENV LD_PRELOAD /lib/MCA-libmath/src/libpreload.so
